fix(voting policy proposal): fix value format for change viting polic…
near-daos/astro-ui pull request #387
Opened 2022-01-10 12:17 UTC by VERZUOL1

…y proposals

2022-01-10 22:24 UTC, AlexeyPonomarenko submitted a review, later dismissed

2022-01-11 06:59 UTC, karpovdmitryod requested changes

2022-01-11 06:59 UTC, dmytro-almighty commented on features/vote-policy/helpers.ts
> +              ((defaulPolicy.ratio[0] / defaulPolicy.ratio[1]) * 100).toFixed(2)
please extract this to separate function

2022-01-11 10:43 UTC, karpovdmitryod approved these changes

2022-01-11 10:44 UTC, merged