feat(comment): parse links and show images in comments
near-daos/astro-ui pull request #390
Opened 2022-01-10 18:46 UTC by VERZUOL1

2022-01-10 19:57 UTC, karpovdmitryod requested changes

2022-01-10 19:57 UTC, karpovdmitryod commented on astro_2.0/features/ViewProposal/components/ProposalComments/components/Comment/Comment.tsx
> +        getImagesFromLinks(links).then(images => {
can you extract it to separate function? 3 if is too much

2022-01-10 22:17 UTC, AlexeyPonomarenko commented on astro_2.0/features/ViewProposal/components/ProposalComments/components/Comment/tests/Comment.spec.tsx
> +describe('App Footer', () => {
I consider we need other describe here)

2022-01-11 10:44 UTC, karpovdmitryod approved these changes

2022-01-11 10:45 UTC, merged